services:
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - config-server

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
      - pecas-service
      - clientes-service
      - representantes-service

  pecas-service:
    build:
      context: ./pecas-service
    container_name: pecas-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server

  clientes-service:
    build:
      context: ./clientes-service
    container_name: clientes-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server

  representantes-service:
    build:
      context: ./representantes-service
    container_name: representantes-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
