# Configurações de teste — desabilita Eureka e Config Server
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:representantesdb-test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

eureka:
  client:
    enabled: false
